# Generated by Django 5.0.7 on 2024-07-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_parameter_alter_shop_options_category_order_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Список заказ'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dt',
            new_name='created_at',
        ),
    ]
