# Generated by Django 5.0.7 on 2024-08-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_productinfo_unique_product_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('basket', 'Статус корзины'), ('new', 'Новый')], max_length=15, verbose_name='Статус'),
        ),
    ]
